variable "disk_name" {}
variable "disk_image" {}
variable "zone" {}
variable "disk_type" {}
variable "disk_size_gb" {}
variable "instance_name" {}
variable "instance_type" {}
variable "tags" {}
variable "network_name" {}
variable "ip_address" {}